name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install the platform-tools
        run: |
          sudo apt install wget -y
          wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
          unzip platform-tools-latest-linux.zip -d ~
          echo -e '\n# add Android SDK platform tools to path\nif [ -d "$HOME/platform-tools" ] ; then\n    PATH="$HOME/platform-tools:$PATH"\nfi' >> ~/.profile
          source ~/.profile

      - name: Preparing your system to build
        run: |
          sudo apt update -y
          sudo apt install git -y
          cd ~/
          git clone https://github.com/akhilnarang/scripts
          cd scripts
          ./setup/android_build_env.sh
          mkdir -p ~/bin
          mkdir -p ~/android/pe
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.email "1141783989zh@gmail.com"
          git config --global user.name "WoLeo-Z"
        
      - name: Initialize the PixelExperience source repository
        run: |
          cd ~/android/pe
          repo init -u https://github.com/PixelExperience/manifest -b thirteen-plus
          
      - name: Download the source code
        run: |
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        
      - name: Prepare the device-specific code
        run: |
          cd ~/android/pe
          source build/envsetup.sh
          lunch aosp_venus-userdebug
        
      - name: Turn on caching to speed up build
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 50G
        
      - name: Start the build
        run: |
          cd ~/android/pe
          croot
          mka bacon -j$(nproc --all)
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            $OUT/recovery.img
            $OUT/PixelExperience_*.zip
        
